### ISSUE TITLE
Wrong reference maybe

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/snowdrop-automation-client#107]
## Question

Why the README.md page includes such a reference `RedHat: Podman can now ease the transition to Kubernetes and CRI-O blog article` ? I dont see the relation with Atomist or maybe ....

**Comment by gytis** [comment]
I think what Antonio means here is that you can use Podman to run an Atomist daemon instead of having it installed locally.

**Comment by cmoulliard** [comment]
FYI: As we will run soon atomist using a Job/container image, using docker or podman will be a matter of detail
