### ISSUE TITLE
Update BOM version upon release

### ISSUE THREAD

**Issue by geoand** [snowdrop/snowdrop-automation-client#2]
after .Final is released, the BOM version should become .SP1-SNAPSHOT

**Comment by geoand** [comment]
@metacosm I suppose that this applies for post-Beta* releases, correct?

**Comment by metacosm** [comment]
See https://github.com/snowdrop/spring-boot-bom/blob/sb-1.5.x/README.md.
Until `.Final` is released, version is, e.g., `1.5.15-SNAPSHOT`. Once `.Final` is released, version becomes `1.5.15.SP1-SNAPSHOT` until we start working on `1.5.16` that is…

**Comment by metacosm** [comment]
Speaking of the BOM README, it also needs to be updated when the versions pointed to are changed as well. We might need to think about a way to do so automatically using a special formatting in the README?

**Comment by geoand** [comment]
@metacosm Gotcha.

I agree about the README formatting, that would probably be the best way to go.
Is there any way one can use "variables" in Markdown?

**Comment by geoand** [comment]
Ideally I would like to have the README be readable at all times, meaning
that it doesn't contain visible placeholders.
But also have a super easy way to update the values of whatever needs to be
updated. That's the reason I asked about variables.

But I am open to doing whatever you think is best. It's a minor issue

**Comment by geoand** [comment]
That really sucks....
