### ISSUE TITLE
Integrate new booster catalogue format in launcher PR command

### ISSUE THREAD

**Issue by aureamunoz** [snowdrop/snowdrop-automation-client#37]
The catalogue format has changed --> https://github.com/fabric8-launcher/launcher-booster-catalog/commit/0f55e29fa19056b13abb155be08d78591709e2a4

We need to adapt our script in order to be able to update the new format catalogue.

**Comment by gytis** [comment]
https://github.com/snowdrop/snowdrop-automation-client/pull/38
