### ISSUE TITLE
Use unique temp branch names

### ISSUE THREAD

**Issue by gytis** [snowdrop/snowdrop-automation-client#41]
Script uses `temp-community` and `temp-product` as temporary branch names during the examples release. If the release fails and branches are not delete all the subsequent releases will also fail until these branches are deleted manually. While keeping the branches to debug failures is useful, we should use a unique prefix to not block subsequent releases.

In addition we should improve logging to notify users about existing temp branches.

**Comment by geoand** [comment]
Makes 100% sense!
