### ISSUE TITLE
Find out why send release email is not sending emails

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/snowdrop-automation-client#59]
Once the client is launched having defined the `SENDGRIDKEY` environment variable, the `SendTestReleaseEmail (Send Test release email) send release email` appears but when it is launched from Slack nothing happens.

**Comment by geoand** [comment]
What do you expect to happen?

IIRC, Libor is the one that receives this email along with one of the spring-boot team lists

**Comment by jacobdotcosta** [comment]
I talked with him and he didn't receive any email. That's why I created this isso, so it is investigated. I have no problem taking a look.

**Comment by geoand** [comment]
OK
