### ISSUE TITLE
Fix launcher pull request creation

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/snowdrop-automation-client#70]
It's now being created manually.

**Comment by gytis** [comment]
For some reason we started getting HTTP request failures when accessing third-party GitHub organisations with our token (it used to work before). We were still able to read them (e.g. to do a rebase) but the token had to be set to null. We were not able to raise a PR without a valid token, however, and as a workaround I have disabled the last step which raises a PR (https://github.com/snowdrop/snowdrop-automation-client/commit/19a4cb9d940c3aa8e787032b7eb6a63ad19e13dc).

**Comment by gytis** [comment]
We either need to authorise Atomist in the launcher catalog repo or configure our personal tokens locally. I've asked Tako if he wouldn't mind us taking the first option, since it would make the configuration much easier.

**Comment by gytis** [comment]
PR: https://github.com/snowdrop/snowdrop-automation-client/pull/89
